### ISSUE TITLE
I2C Driver Need to be implemented

### ISSUE THREAD

**Issue by segfaultdev** [DevHeadsCommunity/FreeRTOS_Gesture_Data_Collection#1]
We are planning to read some data from MPU6050 sensor for example, Acceleration and Gyroscope Data for XYZ axis 

1. We Have To implement the I2C Driver 
2. Then We Have to look for `WHOAMI` register of MPU6050
3. If it can read the `WHOAMI` register then we will move forward with our I2C Driver

**Comment by zacck** [comment]
@undefined2001  this looks good, is there a PR for this yet?

**Comment by segfaultdev** [comment]
@zacck yes there is one

**Comment by zacck** [comment]
@undefined2001  I am confused this is an issue, I thought a PR is a branch of work :)

**Comment by segfaultdev** [comment]
@zacck there is a branch called feature/i2c

**Comment by zacck** [comment]
Yes use that branch open a PR
